#!/usr/bin/env python

import code
import py_algorithms

_PROJECT = 'py-algorithms'

print("")
print("++ {} console v{} started".format(_PROJECT, py_algorithms.__version__))
print("")

code.interact(readfunc=None, local=locals())
